---
title: "GSE150934_Processing"
author: "Tawaun Lucas"
date: "12/12/2022"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    toc_float: true
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---

#GSE150934 - Choi 5XFAD
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(out.width="100%")

library(Seurat)
library(SingleCellExperiment)
library(metaGP)
library(gpExtra)
library(dplyr)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(ggplot2)
library(scDblFinder)
gac <- installedGeneAnnotationCollection("Neuroinflammation")
mouseHipp <- gac$`Mouse Hippocampus scRNASeq Markers`
ga.ctm <- geneSetList(mouseHipp) # "cell type markers"
ga.ctm <- lapply(ga.ctm, unlist) %>% lapply(unname)

```

## Set up funtions for analysis
<details>
<summary>Click for to see code</summary>
```{r Functions}
scoreCells <- function(data,seurat=FALSE,geneSetList=ga.ctm){
for (gene_set in names(geneSetList)) {
score_gene_set <- geneSetList[[gene_set]]
if(seurat==FALSE){
score_gene_set <- intersect(score_gene_set,rownames(data))
scores_by_cell <- colMeans(assay(data, 'logcounts')[score_gene_set,],na.rm = TRUE)
}
if(seurat==TRUE){
data1 <- as.SingleCellExperiment(data)
rownames(data1) <- features$ID
score_gene_set <- intersect(score_gene_set,rownames(data1))
scores_by_cell <- colMeans(assay(data1, 'logcounts')[score_gene_set,],na.rm = TRUE)
}
data[[gene_set]] <- scores_by_cell
}
return(data)
}

runSeurat <- function(obj){
obj <- NormalizeData(obj,verbose=FALSE)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(object = obj, verbose=FALSE)
obj <- RunPCA(obj, npcs = 30,verbose=FALSE)
obj <- FindNeighbors(obj, reduction = "pca",dims=1:20,verbose=FALSE)
obj <- FindClusters(obj, resolution = 0.5,verbose=FALSE)
obj <- RunUMAP(obj,reduction= "pca",dims=1:20,verbose=FALSE)
print("Seurat Pipeline Finished!")
return(obj)
}
```
</details>

# SRR11818958 - WT
```{r}
# load data from the original and filtered h5 file
SRR11818958.raw <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818958.h5", use.names = TRUE)
SRR11818958.filtered <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818958_filtered.h5", use.names = TRUE)

#Create Seurat objects
SRR11818958.raw <- CreateSeuratObject(counts = SRR11818958.raw)
SRR11818958.filtered <- CreateSeuratObject(counts = SRR11818958.filtered)

#lets only look at expression of the same barcoded cells
barcodes <- colnames(SRR11818958.filtered)
SRR11818958.raw <- SRR11818958.raw[,colnames(SRR11818958.raw) %in% barcodes]


feat <- as.data.frame(genomitory::getFeatures("GMTY17:GRCm38/GRCm38.IGIS4.0.genes.rds@REVISION-2"))
x <- match (rownames(SRR11818958.raw),feat$symbol)
features <- feat[x,]

SRR11818958.raw$MitoPercent <- PercentageFeatureSet(SRR11818958.raw, pattern = "^mt-")
SRR11818958.raw$Condition <- "Wildtype"
SRR11818958.raw$Genotype <- "Wildtype"
SRR11818958.raw$StudyID <- "GSE150934"
SRR11818958.raw$Sample <- "SRR11818958"
SRR11818958.raw$Gender <- "Male"
SRR11818958.raw$BrainRegion <- "Hippocampus"
SRR11818958.raw$StudyName <- "Choi 5XFAD"
SRR11818958.raw$data.type <- "Single Cell"
SRR11818958.raw$Age <- "2m"
SRR11818958.raw$Disease <- "AD_control"
SRR11818958.raw$Model <- "Control"

SRR11818958.filtered$MitoPercent <- PercentageFeatureSet(SRR11818958.filtered, pattern = "^mt-")
SRR11818958.filtered$Condition <- "Wildtype"
SRR11818958.filtered$Genotype <- "Wildtype"
SRR11818958.filtered$StudyID <- "GSE150934"
SRR11818958.filtered$Sample <- "SRR11818958"
SRR11818958.filtered$Gender <- "Male"
SRR11818958.filtered$BrainRegion <- "Hippocampus"
SRR11818958.filtered$StudyName <- "Choi 5XFAD"
SRR11818958.filtered$data.type <- "Single Cell"
SRR11818958.filtered$Age <- "2m"
SRR11818958.filtered$Disease <- "AD_control"
SRR11818958.filtered$Model <- "Control"
```
# SRR11818959 - 5xFAD 2 mo
```{r}
# load data from the original and filtered h5 file
SRR11818959.raw <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818959.h5", use.names = TRUE)
SRR11818959.filtered <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818959_filtered.h5", use.names = TRUE)

#Create Seurat objects
SRR11818959.raw <- CreateSeuratObject(counts = SRR11818959.raw)
SRR11818959.filtered <- CreateSeuratObject(counts = SRR11818959.filtered)

#lets only look at expression of the same barcoded cells
barcodes <- colnames(SRR11818959.filtered)
SRR11818959.raw <- SRR11818959.raw[,colnames(SRR11818959.raw) %in% barcodes]


feat <- as.data.frame(genomitory::getFeatures("GMTY17:GRCm38/GRCm38.IGIS4.0.genes.rds@REVISION-2"))
x <- match (rownames(SRR11818959.raw),feat$symbol)
features <- feat[x,]

SRR11818959.raw$MitoPercent <- PercentageFeatureSet(SRR11818959.raw, pattern = "^mt-")
SRR11818959.raw$Condition <- "5XFAD"
SRR11818959.raw$Genotype <- "5XFAD"
SRR11818959.raw$StudyID <- "GSE150934"
SRR11818959.raw$Sample <- "SRR11818959"
SRR11818959.raw$Gender <- "Male"
SRR11818959.raw$BrainRegion <- "Hippocampus"
SRR11818959.raw$StudyName <- "Choi 5XFAD"
SRR11818959.raw$data.type <- "Single Cell"
SRR11818959.raw$Age <- "2m"
SRR11818959.raw$Disease <- "AD"
SRR11818959.raw$Model <- "5XFAD"

SRR11818959.filtered$MitoPercent <- PercentageFeatureSet(SRR11818959.filtered, pattern = "^mt-")
SRR11818959.filtered$Condition <- "5XFAD"
SRR11818959.filtered$Genotype <- "5XFAD"
SRR11818959.filtered$StudyID <- "GSE150934"
SRR11818959.filtered$Sample <- "SRR11818959"
SRR11818959.filtered$Gender <- "Male"
SRR11818959.filtered$BrainRegion <- "Hippocampus"
SRR11818959.filtered$StudyName <- "Choi 5XFAD"
SRR11818959.filtered$data.type <- "Single Cell"
SRR11818959.filtered$Age <- "2m"
SRR11818959.filtered$Disease <- "AD"
SRR11818959.filtered$Model <- "5XFAD"
```
# SRR11818960 - 5xFAD 6 mo
```{r}
# load data from the original and filtered h5 file
SRR11818960.raw <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818960.h5", use.names = TRUE)
SRR11818960.filtered <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818960_filtered.h5", use.names = TRUE)

#Create Seurat objects
SRR11818960.raw <- CreateSeuratObject(counts = SRR11818960.raw)
SRR11818960.filtered <- CreateSeuratObject(counts = SRR11818960.filtered)

#lets only look at expression of the same barcoded cells
barcodes <- colnames(SRR11818960.filtered)
SRR11818960.raw <- SRR11818960.raw[,colnames(SRR11818960.raw) %in% barcodes]


feat <- as.data.frame(genomitory::getFeatures("GMTY17:GRCm38/GRCm38.IGIS4.0.genes.rds@REVISION-2"))
x <- match (rownames(SRR11818960.raw),feat$symbol)
features <- feat[x,]

SRR11818960.raw$MitoPercent <- PercentageFeatureSet(SRR11818960.raw, pattern = "^mt-")
SRR11818960.raw$Condition <- "5XFAD"
SRR11818960.raw$Genotype <- "5XFAD"
SRR11818960.raw$StudyID <- "GSE150934"
SRR11818960.raw$Sample <- "SRR11818960"
SRR11818960.raw$Gender <- "Male"
SRR11818960.raw$BrainRegion <- "Hippocampus"
SRR11818960.raw$StudyName <- "Choi 5XFAD"
SRR11818960.raw$data.type <- "Single Cell"
SRR11818960.raw$Age <- "6m"
SRR11818960.raw$Disease <- "AD"
SRR11818960.raw$Model <- "5XFAD"

SRR11818960.filtered$MitoPercent <- PercentageFeatureSet(SRR11818960.filtered, pattern = "^mt-")
SRR11818960.filtered$Condition <- "5XFAD"
SRR11818960.filtered$Genotype <- "5XFAD"
SRR11818960.filtered$StudyID <- "GSE150934"
SRR11818960.filtered$Sample <- "SRR11818960"
SRR11818960.filtered$Gender <- "Male"
SRR11818960.filtered$BrainRegion <- "Hippocampus"
SRR11818960.filtered$StudyName <- "Choi 5XFAD"
SRR11818960.filtered$data.type <- "Single Cell"
SRR11818960.filtered$Age <- "6m"
SRR11818960.filtered$Disease <- "AD"
SRR11818960.filtered$Model <- "5XFAD"
```
# SRR11818961 - 5xFAD 6 mo
```{r}
# load data from the original and filtered h5 file
SRR11818961.raw <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818961.h5", use.names = TRUE)
SRR11818961.filtered <- Read10X_h5("/gstore/project/neurodegen_meta/data/cellbender/GSE150934/SRR11818961_filtered.h5", use.names = TRUE)

#Create Seurat objects
SRR11818961.raw <- CreateSeuratObject(counts = SRR11818961.raw)
SRR11818961.filtered <- CreateSeuratObject(counts = SRR11818961.filtered)

#lets only look at expression of the same barcoded cells
barcodes <- colnames(SRR11818961.filtered)
SRR11818961.raw <- SRR11818961.raw[,colnames(SRR11818961.raw) %in% barcodes]


feat <- as.data.frame(genomitory::getFeatures("GMTY17:GRCm38/GRCm38.IGIS4.0.genes.rds@REVISION-2"))
x <- match (rownames(SRR11818961.raw),feat$symbol)
features <- feat[x,]

SRR11818961.raw$MitoPercent <- PercentageFeatureSet(SRR11818961.raw, pattern = "^mt-")
SRR11818961.raw$Condition <- "5XFAD"
SRR11818961.raw$Genotype <- "5XFAD"
SRR11818961.raw$StudyID <- "GSE150934"
SRR11818961.raw$Sample <- "SRR11818961"
SRR11818961.raw$Gender <- "Male"
SRR11818961.raw$BrainRegion <- "Hippocampus"
SRR11818961.raw$StudyName <- "Choi 5XFAD"
SRR11818961.raw$data.type <- "Single Cell"
SRR11818961.raw$Age <- "9m"
SRR11818961.raw$Disease <- "AD"
SRR11818961.raw$Model <- "5XFAD"

SRR11818961.filtered$MitoPercent <- PercentageFeatureSet(SRR11818961.filtered, pattern = "^mt-")
SRR11818961.filtered$Condition <- "5XFAD"
SRR11818961.filtered$Genotype <- "5XFAD"
SRR11818961.filtered$StudyID <- "GSE150934"
SRR11818961.filtered$Sample <- "SRR11818961"
SRR11818961.filtered$Gender <- "Male"
SRR11818961.filtered$BrainRegion <- "Hippocampus"
SRR11818961.filtered$StudyName <- "Choi 5XFAD"
SRR11818961.filtered$data.type <- "Single Cell"
SRR11818961.filtered$Age <- "9m"
SRR11818961.filtered$Disease <- "AD"
SRR11818961.filtered$Model <- "5XFAD"
```

# Merge Datasets
```{r warning=FALSE}
raw.data <- merge(x=SRR11818958.raw,y=c(SRR11818959.raw,SRR11818960.raw,SRR11818961.raw),add.cell.ids = c("SRR11818958", "SRR11818959","SRR11818960","SRR11818961"))
raw.data@assays$RNA@meta.features <- features
rownames(raw.data@assays$RNA@meta.features)<- rownames(raw.data)
filtered.data <- merge(x=SRR11818958.filtered,y=c(SRR11818959.filtered,SRR11818960.filtered,SRR11818961.filtered),add.cell.ids = c("SRR11818958", "SRR11818959","SRR11818960","SRR11818961"))
filtered.data@assays$RNA@meta.features <- features
rownames(filtered.data@assays$RNA@meta.features)<- rownames(filtered.data)

```

# Process Datasets
```{r message=FALSE, warning=FALSE}
# Process raw datasets in Seurat
raw.data <- runSeurat(raw.data)
gc()
raw.data <- scoreCells(raw.data, seurat = TRUE)

filtered.data <- runSeurat(filtered.data)
filtered.data <- scoreCells(filtered.data, seurat = TRUE)

```


# Label Astrocytes
```{r Label Astrocytes}
library(SingleR)
library(BiocParallel)
#load reference dataset
ref <- DataSetDB::getDatasetAsSE("DS000002655") #NGS2722 labels
names(assays(ref)) <- c("counts","logcounts")

ref <- ref[,colSums(counts(ref)) > 0]
ref <- ref[,!is.na(ref$biologicalInterest)]
features <- rownames(ref)
symbols <- ref@rowRanges@elementMetadata@listData[["symbol"]]
ref <- as(ref,"SummarizedExperiment")
rownames(ref) <- symbols

filtered.dataSE <- as.SingleCellExperiment(filtered.data)
pred <- SingleR(test = filtered.dataSE, ref = ref,
                  labels = ref$biologicalInterest, de.method="wilcox", BPPARAM = MulticoreParam()  )
filtered.data$FineLabels <- pred$labels
filtered.data$PrunedLabels <- pred$pruned.labels
```

## Plot Umaps
```{r}
p1 <- DimPlot(raw.data,label = TRUE, pt.size=1) + ggtitle("Raw Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold"),legend.position = "none")
p2 <- DimPlot(filtered.data,label=TRUE,pt.size=1) + ggtitle("Filtered Dataset")+
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold"),legend.position = "none")
grid.arrange( p1, p2,nrow=1,top = textGrob("Seurat Clusters",gp=gpar(fontsize=20,font=3)))
```

## Find Astrocytes
```{r message=FALSE, warning=FALSE}
grid.arrange( FeaturePlot(raw.data,features= "astrocyte",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Raw Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "Astrocyte") ,
 FeaturePlot(filtered.data,features= "astrocyte",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Filtered Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "Astrocyte"),
 nrow=1,top = textGrob("Astrocyte Scores",gp=gpar(fontsize=20,font=3)))

grid.arrange( DimPlot(filtered.data,group.by =  "FineLabels",reduction="umap", pt.size = 1, label = TRUE,repel = TRUE) + theme_void() + ggtitle("Cell Labels") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")),
 FeaturePlot(filtered.data,features= "astrocyte",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Filtered Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "Astrocyte"),
 nrow=1,top = textGrob("Astrocyte Scores",gp=gpar(fontsize=20,font=3)))


grid.arrange( FeaturePlot(raw.data,features= "microglia",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Raw Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "microglia") ,
 FeaturePlot(filtered.data,features= "microglia",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Filtered Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "microglia"),
 nrow=1,top = textGrob("Microglia Scores",gp=gpar(fontsize=20,font=3)))

grid.arrange( DimPlot(filtered.data,group.by =  "FineLabels",reduction="umap", pt.size = 1, label = TRUE,repel = TRUE) + theme_void() + ggtitle("Cell Labels") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) ,
 FeaturePlot(filtered.data,features= "microglia",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Filtered Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "Astrocyte"),
 nrow=1,top = textGrob("Astrocyte Scores",gp=gpar(fontsize=20,font=3)))

```

### Expression Plots
```{r message=FALSE, warning=FALSE}
grid.arrange(
  VlnPlot(raw.data,features = "C1qa",group.by = "Model",log = TRUE) + ggtitle("Raw Dataset"),
  VlnPlot(filtered.data,features = "C1qa",group.by = "Model",log=TRUE) + ggtitle("Filtered Dataset"),
  nrow=1,top = textGrob("Expression of C1qa", gp=gpar(fontsize=20,font=3))
)


grid.arrange( FeaturePlot(raw.data,features= "C1qa",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Raw Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "C1qa Expression") ,
 FeaturePlot(filtered.data,features= "C1qa",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Filtered Dataset") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "C1qa Expression"),
 nrow=1,top = textGrob("C1qa Expression",gp=gpar(fontsize=20,font=3)))


```

# Doublet Detection
```{r Run Doublet Finder, message=FALSE}
filtered.data <- subset(filtered.data, subset = nCount_RNA > 10)
raw.data <- subset(raw.data, subset = nCount_RNA > 10)
filtered.sce <- as.SingleCellExperiment(filtered.data)
raw.sce <- as.SingleCellExperiment(raw.data)

filtered.sce <- scDblFinder(filtered.sce,nfeatures = 1500,samples = "Sample")
raw.sce <- scDblFinder(raw.sce,nfeatures = 1500, samples="Sample")


```

# Plot Doublet results

```{r Transfer labels and Plot umap, echo=FALSE, message=FALSE}
filtered.data$scDblFinder.class <- filtered.sce$scDblFinder.class
filtered.data$scDblFinder.score <- filtered.sce$scDblFinder.score
filtered.data$scDblFinder.weighted <- filtered.sce$scDblFinder.weighted
filtered.data$scDblFinder.cxds_score <- filtered.sce$scDblFinder.cxds_score

raw.data$scDblFinder.class <- raw.sce$scDblFinder.class
raw.data$scDblFinder.score <- raw.sce$scDblFinder.score
raw.data$scDblFinder.weighted <- raw.sce$scDblFinder.weighted
raw.data$scDblFinder.cxds_score <- raw.sce$scDblFinder.cxds_score

grid.arrange(
  DimPlot(raw.data, group.by = "scDblFinder.class",pt.size = 1) + ggtitle("Raw Dataset"),
  DimPlot(filtered.data, group.by = "scDblFinder.class",pt.size = 1) + ggtitle("Filtered Dataset"),
  nrow=1,top = textGrob("Doublet Class",gp=gpar(fontsize=20,font=3)))

```

# Subset Astrocytes from filtered data
```{r Astrocytes , fig.show='hold'}

astros <- subset(filtered.data, subset = FineLabels == "astrocyte")
astros <- runSeurat(astros)

grid.arrange(
  DimPlot(astros,label = TRUE, pt.size=1) + ggtitle("Seurat Clusters") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold"),legend.position = "none") ,
  FeaturePlot(astros,features= "astrocyte",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Astrocyte Score") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd"))+labs(colour = "Astrocyte"),
  nrow=1)

grid.arrange(
  FeaturePlot(astros,features = "Gfap",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Gfap") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd")),
  FeaturePlot(astros,features = "Aldh1l1",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Aldh1l1") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd")),
  nrow=1)

grid.arrange(
  FeaturePlot(astros,features = "Gja1",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Gja1") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd")),
  FeaturePlot(astros,features = "Aqp4",reduction="umap", pt.size = 1) +
  theme_void() + ggtitle("Aqp4") +
  theme(plot.title = element_text(hjust = 0.5,size=12,face = "bold")) +
  scale_colour_gradientn(colours = brewer.pal(n = 9, name = "YlOrRd")),
  nrow=1)

```

## Astrocyte numbers
```{r numbers}
print(paste0("There are a total of ", format(dim(astros)[2],big.mark=",",scientific=FALSE),
             " astrocytes.",
             " From which ", format(table(astros$Disease)["AD"],big.mark=",",scientific=FALSE),
             " are Diseased."))

print(paste0("There were a total of ", format(dim(filtered.data)[2],big.mark=",",scientific=FALSE),
             " cells."))

print(paste0("Astrocytes account for ", format( round((dim(astros)[2]/dim(filtered.data)[2])*100,2), big.mark=",",scientific=FALSE),
             "% of cells."))


```
# Save Dataasets
```{r}
saveRDS(astros,"/gstore/project/neurodegen_meta/data/cellbender/GSE150934/Astrocytes.RDS")
saveRDS(filtered.data,"/gstore/project/neurodegen_meta/data/cellbender/GSE150934/filteredData.RDS")
saveRDS(raw.data,"/gstore/project/neurodegen_meta/data/cellbender/GSE150934/rawData.RDS")
```