---
title: "GLP1R_nikhil"
output: html_document
date: "2024-07-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
se_agg <- readRDS("aggregated_cells.AD_MS_PD.070724.DonoruniqueID.Cain_subset_AD_controls.SE.rds")

get_plot_for_gene <- function(se_donorunique_agg, genename) {

  gene = rowData(se_donorunique_agg)[rowData(se_donorunique_agg)$symbol == genename,]$ID
  
  df_mic <- data.frame(expr = t(assay(se_donorunique_agg[gene,],2)), diagnosis = se_donorunique_agg$diagnosis_harmonized, studybatch = se_donorunique_agg$studybatch) %>% dplyr::filter(diagnosis %in% c("PD", "Control"))
  df_mic$diagnosis <- factor(df_mic$diagnosis, levels = c("Control","PD"))

  p <- ggplot(df_mic, aes(diagnosis,!!sym(gene), fill=diagnosis)) + scale_fill_manual(values = c("gray43", "dodgerblue3")) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(width = 0.1)+
    theme(legend.position = "none") + theme_classic() + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)) + ylab("logCPM") + facet_wrap(~ studybatch) + ggtitle(genename)

  return(p)
}

get_plot_for_gene(se_agg[,se_agg$diagnosis_harmonized_by_disease %in% c("PD", "PD_Control")], "GLP1R")
get_plot_for_gene(se_agg[,se_agg$diagnosis_harmonized_by_disease %in% c("PD", "PD_Control")], "GIPR")

```

Get file with cluster/donor pseudobulks

```{r}
se_agg_cluster <- readRDS("aggregated_cells.AD_MS_PD.070724.donorIdUnique_and_cluster.rds")

rowdata <- readRDS("/gstore/scratch/u/novikovg/Astrocytes_meta/AD_MS_PD_cellbender_harmony_2024/harmony_integration/another_run_after_removing_high_mito_clusters/AD_MS_PD_astrocytes.CLEAN_from_non_astrocytes_AND_clusters_high_in_mito.cellbender_counts.20cell_filter.ROWDATA.rds")

coldata <- readRDS("/gstore/scratch/u/novikovg/Astrocytes_meta/AD_MS_PD_cellbender_harmony_2024/harmony_integration/another_run_after_removing_high_mito_clusters/AD_MS_PD_astrocytes.CLEAN_from_non_astrocytes_AND_clusters_high_in_mito.cellbender_counts.20cell_filter.COLDATA.rds")

coldata$diagnosis_harmonized <- ifelse(coldata$diagnosis_harmonized == "RRMS", "MS", coldata$diagnosis_harmonized)

rowdata_agg_cluster <- data.frame(ID = rownames(se_agg_cluster$sums))
rowdata_agg_cluster_final <- left_join(rowdata_agg_cluster, as.data.frame(rowdata) %>% dplyr::select(ID, symbol), by = "ID")

coldata_agg <- as.data.frame(se_agg_cluster$combinations)

### in Bryois, one donor has multiple batches; to be able to left_join, let's overright the Bryois batch for now

coldata[coldata$studybatch == "bryois",]$batch <- NA

coldata_agg_final <-  left_join(coldata_agg, as.data.frame(coldata) %>% dplyr::select(age, diagnosis_harmonized, diagnosis_harmonized_by_disease, sex, studybatch, batch, donorIdUnique) %>% unique, by = c("donor" = "donorIdUnique")) 

se_agg_cluster <- SingleCellExperiment(list(counts=se_agg_cluster$sums),
    colData=coldata_agg_final,
    rowData=rowdata_agg_cluster_final)

y <- DGEList(assay(se_agg_cluster, 1))
y$genes <- data.frame(origin=seq_len(nrow(se_agg_cluster)))
y <- calcNormFactors(y)
se_agg_cluster$lib.size <- y$samples$lib.size
se_agg_cluster$norm.factors <- y$samples$norm.factors
library(gp.sa.diff)
assay(se_agg_cluster, "logCPM") <- normalizedCPM(assay(se_agg_cluster, 1), lib.size=se_agg_cluster$lib.size,
    norm.factors=se_agg_cluster$norm.factors, offset=y$offset)

se_agg_cluster <- se_agg_cluster[,se_agg_cluster$donor %in% se_agg$donor]

saveRDS(se_agg_cluster, "/gstore/scratch/u/novikovg/Astrocytes_meta/AD_MS_PD_cellbender_harmony_2024/harmony_integration/another_run_after_removing_high_mito_clusters/DEGs/aggregated_cells.AD_MS_PD.070724.DonoruniqueID_and_cluster.SE.rds")

```


```{r}

get_plot_for_gene_per_cluster <- function(se_donorunique_agg, genename) {

  gene = rowData(se_donorunique_agg)[rowData(se_donorunique_agg)$symbol == genename,]$ID
  
  df_mic <- data.frame(expr = t(assay(se_donorunique_agg[gene,],2)), cluster = se_donorunique_agg$cluster, studybatch = se_donorunique_agg$studybatch)

  p <- ggplot(df_mic, aes(cluster,!!sym(gene), fill=cluster))+
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(width = 0.1)+
    theme(legend.position = "none") + theme_classic() + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)) + ylab("logCPM") + facet_wrap(~studybatch, ncol= 3)

  return(p)
}

get_plot_for_gene_per_cluster(se_agg_cluster[,se_agg_cluster$diagnosis_harmonized_by_disease %in% c("PD", "PD_Control")], "GLP1R")

get_plot_for_gene(se_agg[,se_agg$diagnosis_harmonized_by_disease %in% c("PD", "PD_Control")], "GIPR")

```

Look into astrocyte signature induced by PFFs in vitro

```{r}
pan_reactive <- c("STEAP4","S1PR3","TIMP1","HSPB1","CXCL10","CD44","OSMR","CP", "SERPINA3","ASPG","VIM","GFAP")
a1_signature <- c("H2-T23","SERPING1","H2-D1","GGTA1","LIGP1","GBP2","FBLN5","UGT1A","FKBP5","PSMB8","SRGN","AMIGO2")
a2_signature <- c("CLCF1","TGM1","PTX3","S100A10","SPHK1","CD109","PTGS2", "EMP1","SLC10A6","TM4SF1","B3GNT5","CD14")


```

